name: if_alz
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  shimmer: ^1.0.1
  confetti: ^0.3.0
  flutter_spinkit: ^4.1.1+1
  cached_network_image: ^2.0.0
  flutter_vector_icons: ^0.2.1
  font_awesome_flutter: ^8.5.0
  flutter_auth_buttons: ^0.6.0
  firebase_auth: ^0.15.4
  cloud_firestore: ^0.13.0+1
  google_sign_in: ^4.1.1
  fluttertoast: ^3.1.3
  shared_preferences: ^0.5.6+1
  cupertino_icons: ^0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - images/
    - ProblemImages/
    # - images/Problem1
    # - images/Prob2
    # - images/Prob3
    # - images/Prob4
    # - images/Prob5
  fonts:
    - family: Quicksand
      fonts:
        - asset: fonts/Quicksand-SemiBold.ttf
        - asset: fonts/Quicksand-Bold.ttf
          weight: 900

    - family: Montserrat
      fonts:
        - asset: fonts/Montserrat/Montserrat-Regular.ttf
        - asset: fonts/Montserrat/Montserrat-ExtraBold.ttf
          weight: 900
